g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/database_operations.d" -MT"src/database_operations.o" -o "src/database_operations.o" "../src/database_operations.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/evaluation.d" -MT"src/evaluation.o" -o "src/evaluation.o" "../src/evaluation.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/file_operations.d" -MT"src/file_operations.o" -o "src/file_operations.o" "../src/file_operations.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/infix_postfix.d" -MT"src/infix_postfix.o" -o "src/infix_postfix.o" "../src/infix_postfix.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/initialize.d" -MT"src/initialize.o" -o "src/initialize.o" "../src/initialize.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/main.d" -MT"src/main.o" -o "src/main.o" "../src/main.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/nested.d" -MT"src/nested.o" -o "src/nested.o" "../src/nested.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/product.d" -MT"src/product.o" -o "src/product.o" "../src/product.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/project.d" -MT"src/project.o" -o "src/project.o" "../src/project.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/rename.d" -MT"src/rename.o" -o "src/rename.o" "../src/rename.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/select.d" -MT"src/select.o" -o "src/select.o" "../src/select.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/set_difference.d" -MT"src/set_difference.o" -o "src/set_difference.o" "../src/set_difference.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/string_modifications.d" -MT"src/string_modifications.o" -o "src/string_modifications.o" "../src/string_modifications.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/syntax_checks.d" -MT"src/syntax_checks.o" -o "src/syntax_checks.o" "../src/syntax_checks.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/table_operations.d" -MT"src/table_operations.o" -o "src/table_operations.o" "../src/table_operations.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/terminal.d" -MT"src/terminal.o" -o "src/terminal.o" "../src/terminal.cpp"
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/union.d" -MT"src/union.o" -o "src/union.o" "../src/union.cpp"
g++  -o "DBMS"  ./src/database_operations.o ./src/evaluation.o ./src/file_operations.o ./src/infix_postfix.o ./src/initialize.o ./src/main.o ./src/nested.o ./src/product.o ./src/project.o ./src/rename.o ./src/select.o ./src/set_difference.o ./src/string_modifications.o ./src/syntax_checks.o ./src/table_operations.o ./src/terminal.o ./src/union.o
